homework_20/Models/TopUpBalance.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace homework_20.Models
{
    public class TopUpBalance
    {
        [Required]
        [Display(Name = "Сумма пополнения")]
        public double Summ { get; set; }

        [Display(Name = "Аккаунт")]
        public int AccNumber { get; set; }
    }
}

homework_20/Models/Transfer.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace homework_20.Models
{
    public class Transfer
    {
        [Required]
        [Display(Name = "Сумма перевода")]
        public double Summ { get; set; }

        [Display(Name = "Аккаунт списания")]
        public int AccNumberFrom { get; set; }
        [Display(Name = "Аккаунт пополнения")]
        public int AccNumberTo { get; set; }
    }
}

homework_20/Controllers/AccountController.cs
using HomeWork_13;
using HomeWork_13.Models;
using homework_20.Models;
using homework_20.Service;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace homework_20.Controllers
{
    [Authorize]
    public class AccountController : Controller
    {
        private readonly UserManager<User> userManager;
        private readonly SignInManager<User> signInManager;
        private readonly DataManager dataManager;
        private readonly ILogger log;
        public AccountController(UserManager<User> userMgr, SignInManager<User> signinMgr, DataManager dataManager, ILogger log)
        {
            userManager = userMgr;
            signInManager = signinMgr;
            this.log = log;
            this.dataManager = dataManager;
        }

        [HttpGet]
        [AllowAnonymous]
        public IActionResult Login(string returnUrl)
        {
            ViewBag.returnUrl = returnUrl;
            return View(new LoginViewModel());
        }
        [HttpPost]
        [AllowAnonymous]
        public async Task<IActionResult> Login(LoginViewModel model, string returnUrl)
        {
            if (ModelState.IsValid)
            {
                User user = await userManager.FindByNameAsync(model.UserName);
                if (user != null)
                {
                    await signInManager.SignOutAsync();
                    Microsoft.AspNetCore.Identity.SignInResult result = await signInManager.PasswordSignInAsync(user, model.Password, model.RememberMe, false);
                    if (result.Succeeded)
                    {
                        log.LogInformation($"Успешная атентификация. редирект: {returnUrl}");
                        return Redirect(returnUrl ?? "/");
                    }
                }
                ModelState.AddModelError(nameof(LoginViewModel.UserName), "Неверный логин или пароль");
            }
            return View(model);
        }

        [Authorize]
        public async Task<IActionResult> Logout()
        {
            log.LogInformation($"Выход из аккаунта: {signInManager.ToString()}");
            await signInManager.SignOutAsync();
            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        [AllowAnonymous]
        public IActionResult Register()
        {
            return View(new UserRegistration());
        }

        [HttpPost, ValidateAntiForgeryToken]
        [AllowAnonymous]
        public async Task<IActionResult> Register(UserRegistration model)
        {
            if (ModelState.IsValid)
            {
                User user = new User { UserName = model.Login, Email = model.Email };
                var createResult = await userManager.CreateAsync(user, model.Password);

                if (createResult.Succeeded)
                {
                    IClient newClient = ClientFactory.GetClient("Client", model.FirstName, model.LastName, DateTime.Parse(model.Birthday), DateTime.Now.Date, 1);
                    
                    dataManager.Clients.SaveClient(newClient);
                    user.idClient = newClient.ID;
                    await userManager.UpdateAsync(user);
                    await signInManager.SignInAsync(user, false);
                    return RedirectToAction("Index", "Home");
                }
                else//иначе
                {
                    foreach (var identityError in createResult.Errors)
                    {
                        ModelState.AddModelError("", identityError.Description);
                    }
                }
            }

            return View(model);
        }
    }

}    

homework_20/Controllers/AccountsController.cs
using homework_20.Models;
using homework_20.Service;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;

namespace homework_20.Controllers
{
    public class AccountsController : Controller
    {
        private readonly DataManager dataManager;
        private readonly UserManager<User> usrMngr;
        private readonly IConfiguration configuration;

        public AccountsController(DataManager dataManager, UserManager<User> usrMngr, IConfiguration configuration)
        {
            this.dataManager = dataManager;
            this.usrMngr = usrMngr;
            this.configuration = configuration;
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> Index()
        {
            ViewBag.TextField = dataManager.TextFields.GetTextFieldByCodeWord("PageAccounts");
            
            User user = await usrMngr.GetUserAsync(User);
            var acc = dataManager.Accounts.GetAccounts((int)user.idClient);

            return View(acc);
        }


        [HttpGet]
        [Authorize]
        public ActionResult OpenAccount()
        {
            User user = usrMngr.Users.FirstOrDefault(x => x.Id == usrMngr.GetUserId(User));

            WebRequest request = WebRequest.Create($"{configuration["Project: WebApiUrl"]}/api/Bank/Account/Create");
            request.Method = "POST"; // для отправки используется метод Post
            // устанавливаем тип содержимого - параметр ContentType
            request.ContentType = "application/json";
            
            string accstring = JsonConvert.SerializeObject(new
            {
                IdClient = user.idClient,
                Balance = 0,
            });
            byte[] byteArray = System.Text.Encoding.UTF8.GetBytes(accstring);

            // Устанавливаем заголовок Content-Length запроса - свойство ContentLength
            request.ContentLength = byteArray.Length;

            //записываем данные в поток запроса
            using (Stream dataStream = request.GetRequestStream())
            {
                dataStream.Write(byteArray, 0, byteArray.Length);
            }

            try
            {
                WebResponse response = request.GetResponse();

                ViewBag.TextField = dataManager.TextFields.GetTextFieldByCodeWord("PageAccounts");
                ViewBag.Text = "Счет успешно откыт!";
                return View("Result");
            }
            catch (WebException e)
            {
                var encoding = ASCIIEncoding.ASCII;
                using (var reader = new System.IO.StreamReader(e.Response.GetResponseStream(), encoding))
                {
                    string responseText = reader.ReadToEnd();
                    ViewBag.Text = $"Не удалось открыть счет. Ошибка: {responseText}";
                    return View("Result");
                }

            }
            
        }


        [HttpGet]
        [Authorize]
        public IActionResult TopUpBalance()
        {
            return View();
        }

        [HttpPost]
        [Authorize]
        public IActionResult TopUpBalance(TopUpBalance model)
        {
            User user = usrMngr.Users.FirstOrDefault(x=>x.Id == usrMngr.GetUserId(User));

            WebRequest request = WebRequest.Create($"{configuration["Project: WebApiUrl"]}/api/Bank/Account/ChangeBalance");
            request.Method = "POST"; // для отправки используется метод Post
            // устанавливаем тип содержимого - параметр ContentType
            request.ContentType = "application/json";


            string accstring = JsonConvert.SerializeObject(new
            {
                id = model.AccNumber,
                summ = model.Summ,
            });
            byte[] byteArray = System.Text.Encoding.UTF8.GetBytes(accstring);

            // Устанавливаем заголовок Content-Length запроса - свойство ContentLength
            request.ContentLength = byteArray.Length;

            //записываем данные в поток запроса
            using (Stream dataStream = request.GetRequestStream())
            {
                dataStream.Write(byteArray, 0, byteArray.Length);
            }
            try
            {
                WebResponse response = request.GetResponse();

                ViewBag.TextField = dataManager.TextFields.GetTextFieldByCodeWord("PageAccounts");
                ViewBag.Text = "Счет успешно пополнен!";
                return View("Result");
            }
            catch (WebException e)
            {
                var encoding = ASCIIEncoding.ASCII;
                using (var reader = new System.IO.StreamReader(e.Response.GetResponseStream(), encoding))
                {
                    string responseText = reader.ReadToEnd();
                    ViewBag.Text = $"Не удалось пополнить счет. Ошибка: {responseText}";
                    return View("Result");
                }                
            }
            
        }

        [HttpGet]
        [Authorize]
        public IActionResult Transfer()
        {
            return View();
        }

        [HttpPost]
        [Authorize]
        public IActionResult Transfer(Transfer model)
        {
            User user = usrMngr.Users.FirstOrDefault(x => x.Id == usrMngr.GetUserId(User));

            WebRequest request = WebRequest.Create($"{configuration["Project: WebApiUrl"]}/api/Bank/Balance/Transfer");
            request.Method = "POST"; // для отправки используется метод Post
            // устанавливаем тип содержимого - параметр ContentType
            request.ContentType = "application/json";


            string accstring = JsonConvert.SerializeObject(new
            {
                fromid = model.AccNumberFrom,
                toid = model.AccNumberTo,
                summ = model.Summ,
            });
            byte[] byteArray = System.Text.Encoding.UTF8.GetBytes(accstring);

            // Устанавливаем заголовок Content-Length запроса - свойство ContentLength
            request.ContentLength = byteArray.Length;

            //записываем данные в поток запроса
            using (Stream dataStream = request.GetRequestStream())
            {
                dataStream.Write(byteArray, 0, byteArray.Length);
            }

            try
            {
                WebResponse response = request.GetResponse();

                ViewBag.TextField = dataManager.TextFields.GetTextFieldByCodeWord("PageAccounts");
                ViewBag.Text = "Успешно выполнен перевод!";
                return View("Result");
            }
            catch (WebException e)
            {
                var encoding = ASCIIEncoding.ASCII;
                using (var reader = new System.IO.StreamReader(e.Response.GetResponseStream(), encoding))
                {
                    string responseText = reader.ReadToEnd();
                    ViewBag.Text = $"Не удалось выполнить перевод. Ошибка: {responseText}";
                    return View("Result");
                }


            }
        }

        
    }
}

homework_20/Views/Accounts/Index.cshtml
@using HomeWork_13.Models
@model IQueryable<IAccount>
@{
    TextField textField = ViewBag.TextField;

    ViewBag.Title = textField.Tittle;
    ViewBag.Description = textField.SubTittle;
}

<div id="results">
    <table class="table-box">
        <tr>
            <th>Номер счета</th>
            <th>Баланс</th>
        </tr>
        @if (Model.Any())
        {

            @foreach (IAccount entity in Model)
            {
                <tr>
                    <td>@entity.ID</td>
                    <td>@entity.Balance</td>
                </tr>
            }
        }
    </table>
</div>

<div>
    <a asp-area="" asp-controller="Accounts" asp-action="TopUpBalance">Пополнить счет</a>
    |
    <a asp-area="" asp-controller="Accounts" asp-action="Transfer">Перевод</a>
    |
    <a id="AccOpen">Открыть счет</a>
</div>


<div class="div-box">

    @*<form asp-area="" asp-controller="Accounts" asp-action="TopUpBalance" method="get">
        <input class="button" type="submit" value="Пополнить счет" />
    </form>

    <form asp-area="" asp-controller="Accounts" asp-action="Transfer" method="get">
        <input class="button" type="submit" value="Перевод" />
    </form>

    <form>
        <input type="submit" class="button" id="AccOpen" value="Открыть счет" />
    </form>*@
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.0/jquery.min.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {

            $("#AccOpen").click(function () {
                $.ajax({
                    type: "Get",
                    dataType: "html",
                    url: "Accounts/OpenAccount",
                    success: function (result) {
                        $('#results').html(result);
                    }
                });
            });
        });
    </script>

</div>

homework_20/Views/Accounts/PartialView.cshtml
@using HomeWork_13.Models
@model IQueryable<IAccount>
@{
    Layout = null;
}

<div id="results">
    <table class="table-box">
        <tr>
            <th>Номер счета</th>
            <th>Баланс</th>
        </tr>
        @if (Model.Any())
        {

            @foreach (IAccount entity in Model)
            {
                <tr>
                    <td>@entity.ID</td>
                    <td>@entity.Balance</td>
                </tr>
            }
        }
    </table>
</div>

homework_20/Views/Accounts/Result.cshtml
<div>
    @Html.Raw(ViewBag.Text)
</div>

homework_20/Views/Accounts/TopUpBalance.cshtml
@model TopUpBalance

<form asp-area="" asp-controller="Accounts" asp-action="TopUpBalance" method="post">
    <div asp-validation-summary="All"></div>
    <div class="form__group field">
        <input asp-for="Summ" type="number" min="0" step="0.01" class="form__field" placeholder="Сумма пополнения" name="Summ" id="summ" required />
        <label for="name" class="form__label">Сумма пополнения</label>
    </div>

    <div class="form__group field">
        <input asp-for="AccNumber" type="number" min="0" class="form__field" placeholder="Номер счета" name="AccNumber" id="accNumber" required />
        <label for="name" class="form__label">Номер счета</label>
    </div>

    <input class="button" type="submit" value="Пополнить счет" />
</form>

homework_20/Views/Accounts/Transfer.cshtml
@model Transfer

<form asp-area="" asp-controller="Accounts" asp-action="Transfer" method="post">
    <div asp-validation-summary="All"></div>


    <div class="form__group field">
        <input asp-for="AccNumberFrom" type="number" min="0" class="form__field" placeholder="Счет отправитель" name="AccNumberFrom" id="accNumber" required />
        <label for="name" class="form__label">Счет отправитель</label>
    </div>

    <div class="form__group field">
        <input asp-for="AccNumberTo" type="number" min="0" class="form__field" placeholder="Счет получатель" name="AccNumberTo" id="accNumber" required />
        <label for="name" class="form__label">Счет получатель</label>
    </div>

    <div class="form__group field">
        <input asp-for="Summ" type="number" min="0" step="0.01" class="form__field" placeholder="Сумма перевода" name="Summ" id="summ" required />
        <label for="name" class="form__label">Сумма</label>
    </div>

    <input class="button" type="submit" value="Выполнить перевод" />
</form>