homework_20/Models/OpenDeposit.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace homework_20.Models
{
    public class OpenDeposit
    {
        [Required]
        [Display(Name = "Сумма пополнения")]
        public double Summ { get; set; }
        [Required]
        [Display(Name = "Аккаунт")]
        public int AccNumber { get; set; }

        [Display(Name = "Дата открытия")]
        public DateTime DateOpen { get; set; }
        
        [Display(Name = "Капитализация")]
        public bool Capitalization { get; set; }

        [Required]
        [Display(Name = "Ставка")]
        public int Rate { get; set; }

        [Required]
        [Display(Name = "Период")]
        public int Period { get; set; }

        [Display(Name = "Клиент")]
        public int IdClient { get; set; }
    }
}

homework_20/Controllers/DepositsController.cs
using HomeWork_13.Models;
using homework_20.Models;
using homework_20.Service;
using hw_22_web_api.Service;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Text;
using System.Threading.Tasks;

namespace homework_20.Controllers
{
    public class DepositsController : Controller
    {
        private readonly DataManager dataManager;
        private readonly UserManager<User> usrMngr;
        private readonly IConfiguration configuration;

        public DepositsController(DataManager dataManager, UserManager<User> usrMngr, IConfiguration configuration)
        {
            this.dataManager = dataManager;
            this.usrMngr = usrMngr;
            this.configuration = configuration;
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> Index()
        {
            ViewBag.TextField = dataManager.TextFields.GetTextFieldByCodeWord("PageDeposits");
            
            User user = await usrMngr.GetUserAsync(User);

            return View(dataManager.Deposits.GetDeposits((int)user.idClient));
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> OpenDeposit()
        {
            User user = await usrMngr.GetUserAsync(User);

            IClient client = dataManager.Clients.GetClientById((int)user.idClient);

            ViewBag.Rates = DepositRate.GetDepositRate(client);
            ViewBag.Periods = DepositPeriod.GetDepositPeriod(client);
            return View();
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> OpenDeposit(OpenDeposit model)
        {
            User user = await usrMngr.GetUserAsync(User);

            IAccount acc = dataManager.Accounts.GetAccountById(model.AccNumber);

            if (acc == null)
            {
                ViewBag.TextField = dataManager.TextFields.GetTextFieldByCodeWord("PageDeposits");
                ViewBag.Text = string.Format("Не удалось открыть депозит. Ошибка: Account with id = {0} not found!", model.AccNumber);
                return View("Result");
            }

            if (acc.Balance < model.Summ)
            {
                ViewBag.TextField = dataManager.TextFields.GetTextFieldByCodeWord("PageDeposits");
                ViewBag.Text = string.Format("Не удалось открыть депозит. Ошибка: Account with id = {0} not enough funds to write off!", model.AccNumber);
                return View("Result");
            }


            WebRequest request = WebRequest.Create($"{configuration["Project:WebApiUrl"]}/api/Bank/Deposit/Create");
            request.Method = "POST"; // для отправки используется метод Post
            // устанавливаем тип содержимого - параметр ContentType
            request.ContentType = "application/json";


            string accstring = JsonConvert.SerializeObject(new
            {
                DateOpen = DateTime.Now,
                IdClient = (int)user.idClient,
                Period = model.Period,
                Capitalization = model.Capitalization,
                Rate = model.Rate,
                Summ = model.Summ,
            });
            byte[] byteArray = System.Text.Encoding.UTF8.GetBytes(accstring);

            // Устанавливаем заголовок Content-Length запроса - свойство ContentLength
            request.ContentLength = byteArray.Length;

            //записываем данные в поток запроса
            using (Stream dataStream = request.GetRequestStream())
            {
                dataStream.Write(byteArray, 0, byteArray.Length);
            }

            try
            {
                WebResponse response = request.GetResponse();

                request = WebRequest.Create($"{configuration["Project:WebApiUrl"]}/api/Bank/Account/DecreaseBalance");
                request.Method = "POST"; // для отправки используется метод Post
                                         // устанавливаем тип содержимого - параметр ContentType
                request.ContentType = "application/json";


                accstring = JsonConvert.SerializeObject(new
                {
                    id = model.AccNumber,
                    summ = model.Summ,
                });
                byteArray = System.Text.Encoding.UTF8.GetBytes(accstring);

                // Устанавливаем заголовок Content-Length запроса - свойство ContentLength
                request.ContentLength = byteArray.Length;

                //записываем данные в поток запроса
                using (Stream dataStream = request.GetRequestStream())
                {
                    dataStream.Write(byteArray, 0, byteArray.Length);
                }

                request.GetResponse();

                ViewBag.TextField = dataManager.TextFields.GetTextFieldByCodeWord("PageDeposits");
                ViewBag.Text = "Депозит успешно открыт!";
                return View("Result");
            }
            catch (WebException e)
            {
                var encoding = ASCIIEncoding.ASCII;
                using (var reader = new StreamReader(e.Response.GetResponseStream(), encoding))
                {
                    string responseText = reader.ReadToEnd();
                    ViewBag.Text = $"Не удалось открыть депозит. Ошибка: {responseText}";
                    return View("Result");
                }

            }
        }
    }
}

homework_20/Views/Deposits/Index.cshtml
@model IQueryable<IDeposit>
@{
    TextField textField = ViewBag.TextField;

    ViewBag.Title = textField.Tittle;
    ViewBag.Description = textField.SubTittle;
}

<div id="results">
    <table class="table-box">
        <tr>
            <th>Вклад</th>
            <th>Сумма</th>
            <th>Период</th>
            <th>Ставка</th>
            <th>Итого</th>
        </tr>
        @if (Model.Any())
        {

            @foreach (IDeposit entity in Model)
            {
                <tr>
                    <td>@entity.ID</td>
                    <td>@entity.Summ</td>
                    <td>@entity.Period</td>
                    <td>@entity.Rate</td>
                    <td>@entity.Outcome</td>
                </tr>
            }

        }
    </table>
</div>
<form asp-area="" asp-controller="Deposits" asp-action="OpenDeposit" method="get">
    <input class="button" type="submit" value="Открыть депозит" />
</form>

homework_20/Views/Deposits/OpenDeposit.cshtml
@model OpenDeposit

<form asp-area="" asp-controller="Deposits" asp-action="OpenDeposit" method="post">
    <div asp-validation-summary="All"></div>


    <div class="form__group field">
        <input asp-for="AccNumber" type="number" min="0" class="form__field" placeholder="Счет списания" name="AccNumber" id="accNumber" required />
        <label for="name" class="form__label">Счет списания</label>
    </div>

    @*<div class="form__group field">
            <input asp-for="Period" type="number" min="0" class="form__field"
            placeholder="Период" name="Period" id="Period" required />
            <label for="name" class="form__label">Период</label>
        </div>*@

    <div class="form__group field">
        @*<input asp-for="Period" type="number" min="0" class="form__field" placeholder="Период селект" name="PeriodSelect" id="Period" required />*@
        <select asp-for="Period" class="form__field" id="Period" required>
            @foreach (var item in ViewBag.Periods)
            {
                <option value="@item.Key">@item.Value</option>
            }
        </select>
        <label for="name" class="form__label">Период</label>
    </div>

    @*<div class="form__group field">
            <input asp-for="Capitalization" type="checkbox" class="form__field" placeholder="Капитализация" name="Capitalization" id="Capitalization" required />
            <label for="name" class="form__label">Капитализация</label>
    </div>*@
    <div class="form__group field">
        <input asp-for="Capitalization" name="Capitalization" id="Capitalization" type="checkbox" class="switch">
        <label for="Capitalization">Капитализация</label>
    </div>
    @*<label class="checkbox-other">
        <input asp-for="Capitalization" name="Capitalization" id="Capitalization" type="checkbox"> Капитализация
    </label>*@

    @*<div class="form__group field">
            <input asp-for="Rate" type="number" min="0" class="form__field" placeholder="Ставка" name="Rate" id="Rate" required />
            <label for="name" class="form__label">Ставка</label>
        </div>*@

    <div class="form__group field">
        <select asp-for="Rate" class="form__field" id="Rate" required>
            @foreach (var item in ViewBag.Rates)
            {
                <option value="@item.Key">@item.Value</option>
            }
        </select>
        <label for="name" class="form__label">Ставка</label>
    </div>

    <div class="form__group field">
        <input asp-for="Summ" type="number" min="0" step="0.01" class="form__field" placeholder="Сумма перевода" name="Summ" id="summ" required />
        <label for="name" class="form__label">Сумма</label>
    </div>

    <input class="button" type="submit" value="Открыть вклад" />
</form>

homework_20/Views/Deposits/Result.cshtml
<div>
    @Html.Raw(ViewBag.Text)
</div>