homework_20/Models/Entity/ServiceItem.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace homework_20.Models.Entity
{
    public class ServiceItem : EntityBase
    {
        [Required(ErrorMessage = "Заполните наименование услуги")]

        [Display(Name = "Наименование услуги")]
        public override string Tittle { get; set; }

        [Display(Name = "Описание услуги")]
        public override string SubTittle { get; set; }

        [Display(Name = "Содержание услуги")]
        public override string Text { get; set; }

        [Required(ErrorMessage = "Заполните тип услуги")]
        [Display(Name = "Тип услуги")]
        public string ServiceType { get; set; }

    }

}

homework_20/Areas/Admin/Controllers/ServiceItemsController.cs
using homework_20.Admin.Controllers;
using homework_20.Models;
using homework_20.Models.Entity;
using homework_20.Service;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace homework_20.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ServiceItemsController : Controller
    {
        private readonly DataManager dataManager;
        private readonly IWebHostEnvironment hostingEnvironment;
        public ServiceItemsController(DataManager dataManager, IWebHostEnvironment hostingEnvironment)
        {
            this.dataManager = dataManager;
            this.hostingEnvironment = hostingEnvironment;
        }

        public IActionResult Edit(Guid id)
        {
            SelectList serviceTypes = new SelectList(ServiceType.GetServiceTypes(), "Key", "Value");
            ViewData["ServiceTypes"] = serviceTypes;

            var entity = id == default ? new ServiceItem() : dataManager.ServiceItems.GetServiceItemById(id);
            return View(entity);
        }
        [HttpPost]
        public IActionResult Edit(ServiceItem model, IFormFile ImageFile)
        {
            if (ModelState.IsValid)
            {
                if (ImageFile != null)
                {
                    model.ImagePath = ImageFile.FileName;
                    using (var stream = new FileStream(Path.Combine(hostingEnvironment.WebRootPath, "images/", ImageFile.FileName), FileMode.Create))
                    {
                        ImageFile.CopyTo(stream);
                    }
                }
                dataManager.ServiceItems.SaveServiceItem(model);
                return RedirectToAction(nameof(HomeController.Index), nameof(HomeController).CutController());
            }
            SelectList serviceTypes = new SelectList(ServiceType.GetServiceTypes(), "Key", "Value");
            ViewData["ServiceTypes"] = serviceTypes;
            return View(model);
        }

        [HttpPost]
        public IActionResult Delete(Guid id)
        {
            dataManager.ServiceItems.DeleteServiceItem(id);
            return RedirectToAction(nameof(HomeController.Index), nameof(HomeController).CutController());
        }
    }
}

homework_20/Areas/Admin/Views/ServiceItems/Edit.cshtml
@model ServiceItem
@{
    string strTitle = "Редактировать запись";
    ViewBag.Title = strTitle;
}

<script src="~/js/ckeditor/ckeditor.js"></script>

<div>
    <h2>@strTitle</h2>
    <div>
        <form asp-area="Admin" asp-controller="ServiceItems" asp-action="Edit" method="post" enctype="multipart/form-data">
            <input type="hidden" asp-for="Id" />
            <input type="hidden" asp-for="DateAdd" />
            <input type="hidden" asp-for="ImagePath" />

            <div asp-validation-summary="All"></div>
            <div class="div-box">
                <label asp-for="Tittle"></label>
                <input asp-for="Tittle" />
                <span asp-validation-for="Tittle"></span>
            </div>
            <div class="div-box" >
                <label asp-for="ServiceType"></label>
                @Html.DropDownListFor(Model => Model.ServiceType, ViewData["ServiceTypes"] as SelectList, "-Выберите значение-")                
                <span asp-validation-for="ServiceType"></span>
            </div>
            <div class="div-box">
                <label asp-for="SubTittle"></label>
                <input asp-for="SubTittle" />
                <span asp-validation-for="SubTittle"></span>
            </div>
            <div class="div-box">
                <label asp-for="Text"></label>
                <textarea asp-for="Text"></textarea>
                <span asp-validation-for="Text"></span>
            </div>
            <div class="div-box">
                <label asp-for="ImagePath"></label>
                <input type="file" name="ImageFile" id="ImageFile" />
                <div>
                    <img class="img-block" src="~/images/@Model.ImagePath" />
                </div>
            </div>
            <input type="submit" value="Сохранить" />
        </form>
    </div>
</div>



<script>
    window.onload = function() {
        var newCKEdit = CKEDITOR.replace('@Html.IdFor(x=>x.Text)');
        newCKEdit.updateElement();
    }
</script>